/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Color;

/**
 *
 * @author LEFT4
 */
public class EntradaCentro extends javax.swing.JFrame {

    /**
     * Creates new form EntradaCentro
     */
    public EntradaCentro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Carrito = new javax.swing.JButton();
        btn_Heladeria = new javax.swing.JButton();
        btn_Electronica = new javax.swing.JButton();
        brtn_Relojeria = new javax.swing.JButton();
        msjBienvenida = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Carrito.setText("Carrito");
        jPanel1.add(btn_Carrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 80, 30));

        btn_Heladeria.setText("Heladeria");
        btn_Heladeria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_HeladeriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_HeladeriaMouseExited(evt);
            }
        });
        jPanel1.add(btn_Heladeria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 380));

        btn_Electronica.setText("Electronica");
        jPanel1.add(btn_Electronica, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 210, 380));

        brtn_Relojeria.setText("Relojeria");
        jPanel1.add(brtn_Relojeria, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 210, 380));

        msjBienvenida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        msjBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        msjBienvenida.setText("Buen dia (nombre)! Bienvenido al Centro Comercial!");
        jPanel1.add(msjBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoInicio.jpg"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HeladeriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HeladeriaMouseEntered
//        btn_Heladeria.setBackground(Color.red);
    }//GEN-LAST:event_btn_HeladeriaMouseEntered

    private void btn_HeladeriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HeladeriaMouseExited
//        btn_Heladeria.setBackground(Color.blue);
    }//GEN-LAST:event_btn_HeladeriaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntradaCentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntradaCentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntradaCentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntradaCentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntradaCentro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton brtn_Relojeria;
    private javax.swing.JButton btn_Carrito;
    private javax.swing.JButton btn_Electronica;
    private javax.swing.JButton btn_Heladeria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel msjBienvenida;
    // End of variables declaration//GEN-END:variables
}
