/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyecto.vistas;

import javax.swing.JButton;

/**
 *
 * @author Javier
 */
public class vistaMenu extends javax.swing.JPanel {

    /**
     * Creates new form vistaMenu
     */
    public vistaMenu() {
        initComponents();
    }

    public JButton getBtn_Carrito() {
        return btn_Carrito;
    }

    public JButton getBtn_Electronica() {
        return btn_Electronica;
    }

    public JButton getBtn_Heladeria() {
        return btn_Heladeria;
    }

    public JButton getBtn_Relojeria() {
        return btn_Relojeria;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Carrito = new javax.swing.JButton();
        btn_Relojeria = new javax.swing.JButton();
        btn_Electronica = new javax.swing.JButton();
        btn_Heladeria = new javax.swing.JButton();
        msjBienvenida = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        btn_Carrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyecto/imagenes/carro-de-la-compra (1).png"))); // NOI18N

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Relojeria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyecto/imagenes/RelojeriaLOGO.png"))); // NOI18N
        add(btn_Relojeria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 430, 180));

        btn_Electronica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyecto/imagenes/ElectronicaLOGO.png"))); // NOI18N
        add(btn_Electronica, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 430, 180));

        btn_Heladeria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyecto/imagenes/HeladeriaLOGO.png"))); // NOI18N
        add(btn_Heladeria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 200, 380));

        msjBienvenida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        msjBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        msjBienvenida.setText("Buen dia (nombre)! Bienvenido al Centro Comercial!");
        add(msjBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyecto/imagenes/FondoCentro.png"))); // NOI18N
        add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 450));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btn_Carrito;
    private javax.swing.JButton btn_Electronica;
    private javax.swing.JButton btn_Heladeria;
    private javax.swing.JButton btn_Relojeria;
    private javax.swing.JLabel msjBienvenida;
    // End of variables declaration//GEN-END:variables
}
