package com.proyecto.vistas;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author LEFT4
 */
public class VistaCentro extends javax.swing.JFrame {

    /**
     * Creates new form EntradaCentro
     */
    public VistaCentro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public JLabel getjLSaludo() {
        return jLSaludo;
    }

    public JLabel getjLAtras() {
        return jLAtras;
    }

    public JLabel getjLCarrito() {
        return jLCarrito;
    }

    public JButton getBtn_Electronica() {
        return btn_Electronica;
    }

    public JButton getBtn_Heladeria() {
        return btn_Heladeria;
    }

    public JButton getBtn_Relojeria() {
        return btn_Relojeria;
    }

    public JLabel getMsjBienvenida() {
        return jLSaludo;
    }

    public JLabel getjLListaClientes() {
        return jLListaClientes;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLSaludo = new javax.swing.JLabel();
        btn_Heladeria = new javax.swing.JButton();
        btn_Electronica = new javax.swing.JButton();
        btn_Relojeria = new javax.swing.JButton();
        jLCarrito = new javax.swing.JLabel();
        jLAtras = new javax.swing.JLabel();
        jLListaClientes = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLSaludo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLSaludo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLSaludo.setText("Buen dia (nombre)! Bienvenido al Centro Comercial!");
        jPanel1.add(jLSaludo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 480, 60));

        btn_Heladeria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyecto/imagenes/HeladeriaLOGO.png"))); // NOI18N
        jPanel1.add(btn_Heladeria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 200, 380));

        btn_Electronica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyecto/imagenes/ElectronicaLOGO.png"))); // NOI18N
        jPanel1.add(btn_Electronica, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 430, 180));

        btn_Relojeria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyecto/imagenes/RelojeriaLOGO.png"))); // NOI18N
        jPanel1.add(btn_Relojeria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 430, 180));

        jLCarrito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyecto/imagenes/carrito.png"))); // NOI18N
        jPanel1.add(jLCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 5, 50, 50));

        jLAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyecto/imagenes/icons8_undo_50px_1.png"))); // NOI18N
        jLAtras.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 50, 50));

        jLListaClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLListaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyecto/imagenes/icons8_user_menu_female_50px.png"))); // NOI18N
        jPanel1.add(jLListaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 5, 50, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyecto/imagenes/FondoCentro.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCentro().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btn_Electronica;
    private javax.swing.JButton btn_Heladeria;
    private javax.swing.JButton btn_Relojeria;
    private javax.swing.JLabel jLAtras;
    private javax.swing.JLabel jLCarrito;
    private javax.swing.JLabel jLListaClientes;
    private javax.swing.JLabel jLSaludo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
